version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: iam_postgres
    environment:
      POSTGRES_DB: iam_db
      POSTGRES_USER: iam_user
      POSTGRES_PASSWORD: iam_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - iam_network

  # Backend NestJS
  backend:
    build:
      context: ./iam-backend
      dockerfile: Dockerfile
    container_name: iam_backend
    environment:
      DATABASE_URL: postgresql://iam_user:iam_password@postgres:5432/iam_db
      JWT_SECRET: your_jwt_secret_here
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - iam_network
    restart: unless-stopped

  # Frontend Next.js
  frontend:
    build:
      context: ./iam-frontend
      dockerfile: Dockerfile
    container_name: iam_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - iam_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  iam_network:
    driver: bridge
