# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    container_name: IAM
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: inventario_iam
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
