version: '3.8'

services:
  db:
    image: postgres:15
    container_name: IAM
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: inventario_iam
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./iam-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./iam-frontend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./iam-backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./iam-backend:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

