FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install -g @nestjs/cli && \
    npm install && \
    npx prisma generate

COPY . .

EXPOSE 3001

CMD ["npm", "run", "start:docker"]
